### PR TITLE
Compound directives

### PR DESCRIPTION
**Pull request by tsibley**
See https://rt.cpan.org/Ticket/Display.html?id=90643

### CODE REVIEW

**Comment by bluefeet** [comment]
Yo - I'm now a comaintainer of this module.  I've taken a look at what you did, and while I like the idea, I was worried that it wasn't smart enough.  I also question if there is a better way, as munging the source TT code is something the light-hearted should not attempt.  :)

So, I ran your version of Template::AutoFilter against a popular Perl/TT website which uses the module and got an error instantly.  It seems that it dies when it runs into code like this (simple example):

[% foo=1; %]

If I remove the semicolon it seems to work fine.  But, I haven't tested much deeper.  The error I get is:

Couldn't render template "X: file error - parse error - Y line 1: unexpected end of input"

**Comment by bluefeet** [comment]
I did merge the first two commits which were good.  A new release should be propagating out to the CPAN mirrors soon.

**Comment by tsibley** [comment]
Thanks for merging the first two commits.  I pushed two more commits onto this branch which fix the bug you found.  I have not yet had a chance to use this plugin myself, so as much testing and kicking the tires as possible is great!

Munging the TT parsed tokens is definitely black magic territory, but that's how the module worked before I got here and I don't see another good way.  It's the best available option when I was looking into this months ago.  My branch does expand the number of cases which have the autofilter applied and so is likely to run into more corner cases.

**Comment by wchristian** [comment]
Since your two commits modify the previous commit, could you please merge them and amend them into the first one, then force push that? There is little value in keeping between-release steps in the commit history. :)

**Comment by tsibley** [comment]
@wchristian: All commits modify previous commits. ;) I squashed the commits, rebased onto your current master, and force pushed my branch.

**Comment by tsibley** [comment]
Ping?

**Comment by wchristian** [comment]
Apologies for forgetting about this. After fixing some dzil dependencies, i just pushed a release with your fix to CPAN. :)

**Pull request closed without merging**
